matrix:
  VERSION:
    - "1.1.0"

build:
  image: armhfbuild/swarm-dev:$$VERSION
  commands:
    - git clone --single-branch https://github.com/docker/swarm-library-image upstream
    - cp /go/bin/swarm upstream/swarm

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    context: upstream
    file: upstream/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/swarm
    tag:
      - latest
      - "1.1.0"
    when:
      matrix:
        VERSION: "1.1.0"

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
