matrix:
  VERSION:
    - "1.1.0"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    # FIXME Replace this mess with a better docker-dind based build plugin
    - docker daemon -s aufs -g /drone/docker &
    - sleep 2
    - docker daemon -s overlay -g /drone/docker &
    - apk add --update git
    - git clone --single-branch https://github.com/docker/swarm-library-image upstream
    - docker run --rm --entrypoint /bin/cat armhfbuild/swarm-dev:$$VERSION /go/bin/swarm >upstream/swarm
    - chmod u+x upstream/swarm

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    context: upstream
    file: upstream/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/swarm
    tag:
      - latest
      - "1.1.0"
    when:
      matrix:
        VERSION: "1.1.0"

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
